# https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#create-env-file-manually
name: demandmap_plotting
channels:
  - conda-forge
  - nodefaults
dependencies:
  # core funcitonality
  - python=3.12
  # data science
  - jupyterlab
  - scipy
  - pandas
  - numpy
  - openpyxl
  # plotting
  - matplotlib
  # geospatial plotting
  - geopandas
  - cartopy
  - shapely
  - country_converter
  - matplotlib-scalebar
  - contextily
  - rasterio
  # statistics
  - eurostat